#!/bin/bash

INFLUXDB_USERNAME=${INFLUXDB_USERNAME:-"influx"}
INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-"123456789"}
INFLUXDB_ORG=${INFLUXDB_ORG:-"acme"}
INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-"my-bucket"}
INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-"00000000-0000-0000-0000-000000000000"}

docker run -ti --rm \
    --name influxdb \
    -p 8086:8086 \
    -e DOCKER_INFLUXDB_INIT_MODE=setup \
    -e DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME} \
    -e DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD} \
    -e DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG} \
    -e DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET} \
    -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN} \
    influxdb:2.6-alpine
